# Generated by Django 5.2.9 on 2025-12-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
